---
- name: restart wazuh-manager
  ansible.builtin.sysvinit:
    name: wazuh-manager
    state: restarted
    enabled: true

- name: restart wazuh-api
  ansible.builtin.sysvinit:
    name: wazuh-api
    state: restarted
    enabled: true
