---
  - name: Install Wazuh Agent from .deb packages
    apt:
      deb: "{{ wazuh_custom_packages_installation_agent_deb_url }}"
      state: present
    when:
      - ansible_os_family|lower == "debian"
      - wazuh_custom_packages_installation_agent_enabled

  - name: Install Wazuh Agent from .rpm packages | yum
    yum:
      name: "{{ wazuh_custom_packages_installation_agent_rpm_url }}"
      state: present
    when:
      - ansible_os_family|lower == "redhat"
      - wazuh_custom_packages_installation_agent_enabled
      - not (ansible_distribution|lower == "centos" and ansible_distribution_major_version >= "8")
      - not (ansible_distribution|lower == "redhat" and ansible_distribution_major_version >= "8")

  - name: Install Wazuh Agent from .rpm packages | dnf
    dnf:
      name: "{{ wazuh_custom_packages_installation_agent_rpm_url }}"
      state: present
    when:
      - ansible_os_family|lower == "redhat"
      - wazuh_custom_packages_installation_agent_enabled
      - (ansible_distribution|lower == "centos" and ansible_distribution_major_version >= "8") or
        (ansible_distribution|lower == "redhat" and ansible_distribution_major_version >= "8")

# Solaris
  - name: Create noask file
    lineinfile:
      path: "/export/home/vagrant/noaskfile"
      line: action=nocheck
      create: yes
    when: ansible_os_family == "Solaris"

  - name: Install solaris wazuh agent custom package
    become: true
    shell: pkgadd -a noaskfile -d wazuh-* -n all
    environment:
      PATH: "/opt/python3/bin/:/usr/sbin:/usr/bin:/usr/sbin/:/opt/csw/gnu/:/usr/sfw/bin/:/opt/csw/bin/"
    args:
      chdir: "/export/home/vagrant"
    when: ansible_os_family == 'Solaris'

# Windows
  - name: Install Wazuh Agent from .msi packages | custom win_package
    win_package:
      path: "{{ wazuh_custom_packages_installation_agent_msi_url }}"
      state: present
    when:
      - ansible_os_family == "Windows"
      - wazuh_custom_packages_installation_agent_enabled
